services:

  app_proxy:
    environment:
      APP_HOST: ${APP_ID}_web_1
      APP_PORT: 3000

  web:
    build:
      context: ${APP_DATA_DIR}/app
    restart: on-failure
    stop_grace_period: 1m
    environment:
      KS_USER: admin
      KS_PASSWORD: "12345678"
